"""empty message

Revision ID: 116b1037f788
Revises: d16b886bee27
Create Date: 2022-03-23 19:11:32.392775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116b1037f788'
down_revision = 'd16b886bee27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('recipient_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('chat_participation')
    op.drop_table('users')
    op.drop_table('chats')
    # ### end Alembic commands ###
