"""empty message

Revision ID: 235d0f0e1c6c
Revises: eb4d500340b0
Create Date: 2022-04-01 14:22:53.011256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235d0f0e1c6c'
down_revision = 'eb4d500340b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'can_edit_db_notifications')
    op.drop_column('roles', 'can_edit_db_users')
    op.drop_column('roles', 'can_edit_db_roles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('can_edit_db_roles', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('can_edit_db_users', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('can_edit_db_notifications', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
