"""empty message

Revision ID: eb4d500340b0
Revises: c1ec40fb6055
Create Date: 2022-03-31 21:25:32.121220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb4d500340b0'
down_revision = 'c1ec40fb6055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('can_edit_db_roles', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('can_edit_db_users', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('can_edit_db_notifications', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'can_edit_db_notifications')
    op.drop_column('roles', 'can_edit_db_users')
    op.drop_column('roles', 'can_edit_db_roles')
    # ### end Alembic commands ###
